### ISSUE TITLE
Kibana Elastalert Plugin won't save Rules

### ISSUE THREAD

**Issue by joel858** [cisagov/Malcolm#105]
When creating new elastalert rule, when I save I get internal server error 500.  Tailing the logs for malcolm_kibana_1 doesn't provide much more information. 

The kibana container is running in an "unhealthy state", however I'm not sure if the health check is accurate. The http redirect from the nginx proxy might not work, however, when curl -u "username":"password" -kf https://"hostname":5601/api/status it returns the status.

**Comment by mmguero** [comment]
What version of Malcolm are you running (`docker images | grep malcolm`)? I did have an issue with the Kibana health check not using the right URL (and a few things with elastalert, too, if I recall) that was fixed in v1.8.1 a couple of weeks ago.

**Comment by joel858** [comment]
I'm running 1.8. If I upgrade to 1.8.1, Uploading the images and updating the docker-compose is all I need to do? Or do I need to do a complete reinstall?

What elastalert issue did you run into? What fixes did make in the newer version?

**Comment by mmguero** [comment]
Yeah I _think_ updating the docker-compose files and pulling the new images should be all you have to do.

As far as elastalert goes, to get things working with Elastic 7.5 I ended up forking the `bitsensor/elastalert` container and [making some fixes to it](https://github.com/bitsensor/elastalert/compare/master...mmguero-dev:master). So it's a newer version of elastalert and the base is newer also. TBH most of the rest of the changes in 1.8.1 is dealing with updating elastic to the new version.

I'm right in the middle of working on something else at the moment but when I get a sec I'll run through a clean install of Malcolm through creating and saving an elastalert rule and make sure it all works for me. If it does I'll post the debug output here.

**Comment by mmguero** [comment]
I did a clean clone/pull of Malcolm v1.8.1 last night and tested saving an elastalert rule. Here's the debug output from my docker containers during the edit/save (separated out by service):

Elastalert:
```
elastalert_1     | 14:56:53.080Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules'.
elastalert_1     | 14:57:28.518Z  INFO elastalert-server: Routes:  Successfully handled POST request for '/rules/:id'.
elastalert_1     | 14:57:28.572Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules'.
elastalert_1     | catched
```

Kibana:
```
kibana_1         | {"type":"response","@timestamp":"2020-01-24T14:56:53Z","tags":[],"pid":90,"method":"get","statusCode":200,"req":{"url":"/api/elastalert/rules","method":"get","headers":{"host":"kibana.malcolm.local","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","accept":"application/json, text/plain, */*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","kbn-version":"7.5.1","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"remoteAddress":"172.20.0.14","userAgent":"172.20.0.14","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"res":{"statusCode":200,"responseTime":9,"contentLength":9},"message":"GET /api/elastalert/rules 200 9ms - 9.0B"}
kibana_1         | {"type":"response","@timestamp":"2020-01-24T14:56:53Z","tags":[],"pid":90,"method":"get","statusCode":200,"req":{"url":"/bundles/132.bundle.js","method":"get","headers":{"host":"kibana.malcolm.local","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"remoteAddress":"172.20.0.14","userAgent":"172.20.0.14","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"res":{"statusCode":200,"responseTime":4,"contentLength":9},"message":"GET /bundles/132.bundle.js 200 4ms - 9.0B"}
kibana_1         | {"type":"response","@timestamp":"2020-01-24T14:56:53Z","tags":[],"pid":90,"method":"get","statusCode":200,"req":{"url":"/bundles/178.bundle.js","method":"get","headers":{"host":"kibana.malcolm.local","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"remoteAddress":"172.20.0.14","userAgent":"172.20.0.14","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"res":{"statusCode":200,"responseTime":6,"contentLength":9},"message":"GET /bundles/178.bundle.js 200 6ms - 9.0B"}
kibana_1         | {"type":"response","@timestamp":"2020-01-24T14:56:53Z","tags":[],"pid":90,"method":"get","statusCode":200,"req":{"url":"/bundles/237.bundle.js","method":"get","headers":{"host":"kibana.malcolm.local","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"remoteAddress":"172.20.0.14","userAgent":"172.20.0.14","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"res":{"statusCode":200,"responseTime":4,"contentLength":9},"message":"GET /bundles/237.bundle.js 200 4ms - 9.0B"}
kibana_1         | {"type":"response","@timestamp":"2020-01-24T14:56:55Z","tags":[],"pid":90,"method":"get","statusCode":200,"req":{"url":"/bundles/86.bundle.js","method":"get","headers":{"host":"kibana.malcolm.local","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"remoteAddress":"172.20.0.14","userAgent":"172.20.0.14","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"res":{"statusCode":200,"responseTime":4,"contentLength":9},"message":"GET /bundles/86.bundle.js 200 4ms - 9.0B"}
kibana_1         | {"type":"response","@timestamp":"2020-01-24T14:57:28Z","tags":[],"pid":90,"method":"get","statusCode":200,"req":{"url":"/api/elastalert/rules","method":"get","headers":{"host":"kibana.malcolm.local","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","accept":"application/json, text/plain, */*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","kbn-version":"7.5.1","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"remoteAddress":"172.20.0.14","userAgent":"172.20.0.14","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"res":{"statusCode":200,"responseTime":3,"contentLength":9},"message":"GET /api/elastalert/rules 200 3ms - 9.0B"}
kibana_1         | {"type":"response","@timestamp":"2020-01-24T14:57:28Z","tags":[],"pid":90,"method":"post","statusCode":200,"req":{"url":"/api/elastalert/rules/notice","method":"post","headers":{"host":"kibana.malcolm.local","connection":"close","content-length":"1707","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","accept":"application/json, text/plain, */*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","content-type":"application/json;charset=utf-8","kbn-version":"7.5.1","origin":"https://localhost","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"remoteAddress":"172.20.0.14","userAgent":"172.20.0.14","referer":"https://localhost/kibana/app/elastalert-kibana-plugin"},"res":{"statusCode":200,"responseTime":26,"contentLength":9},"message":"POST /api/elastalert/rules/notice 200 26ms - 9.0B"}
```

nginx:
```
nginx-proxy_1    | 172.20.0.1 - admin [24/Jan/2020:14:56:53 +0000] "GET /kibana/api/elastalert/rules HTTP/1.1" 200 40 "https://localhost/kibana/app/elastalert-kibana-plugin" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
nginx-proxy_1    | 172.20.0.1 - admin [24/Jan/2020:14:56:53 +0000] "GET /kibana/bundles/132.bundle.js HTTP/1.1" 200 990 "https://localhost/kibana/app/elastalert-kibana-plugin" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
nginx-proxy_1    | 172.20.0.1 - admin [24/Jan/2020:14:56:53 +0000] "GET /kibana/bundles/178.bundle.js HTTP/1.1" 200 990 "https://localhost/kibana/app/elastalert-kibana-plugin" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
nginx-proxy_1    | 172.20.0.1 - admin [24/Jan/2020:14:56:53 +0000] "GET /kibana/bundles/237.bundle.js HTTP/1.1" 200 662 "https://localhost/kibana/app/elastalert-kibana-plugin" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
nginx-proxy_1    | 172.20.0.1 - admin [24/Jan/2020:14:56:55 +0000] "GET /kibana/bundles/86.bundle.js HTTP/1.1" 200 645 "https://localhost/kibana/app/elastalert-kibana-plugin" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
nginx-proxy_1    | 172.20.0.1 - admin [24/Jan/2020:14:57:28 +0000] "GET /kibana/api/elastalert/rules HTTP/1.1" 200 48 "https://localhost/kibana/app/elastalert-kibana-plugin" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
nginx-proxy_1    | 172.20.0.1 - admin [24/Jan/2020:14:57:28 +0000] "POST /kibana/api/elastalert/rules/notice HTTP/1.1" 200 41 "https://localhost/kibana/app/elastalert-kibana-plugin" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
```

Here was my test rule:
```
name: notice

type: any

realert:
  minutes: 5
query_key: [zeek.uid, zeek_notice.note]

index: sessions2-*
doc_type: session
timestamp_field: "@timestamp"
timestamp_type: iso
filter:
 - query:
      query_string:
        query: "zeek.logType:notice AND (NOT zeek_notice.note:\"SSL::Invalid_Server_Cert\")"

alert_subject: "{0} notice from {1}"
alert_subject_args: ["zeek_notice.note", "host.name"]

alert_text_type: alert_text_only
alert_text: "Network traffic captured by {0} generated a {1} notice at {2}: \"{3}\""
alert_text_args: ["host.name", "zeek_notice.note", "zeek.ts", "zeek_notice.msg"]

alert:
  - command
command: ["/bin/cat"]
pipe_alert_text: true
```

This was with Firefox 72.0.2 on Linux.

**Comment by mmguero** [comment]
Hmmmm... after a few minutes I did get an error in the `elastalert` container though. I will track it down, I may have to rebuild that container and/or do a minor update, I thought I had caught this issue before the release:

```
elastalert_1     | 15:06:46.697Z ERROR elastalert-server:
elastalert_1     |     ProcessController:  ERROR:root:Traceback (most recent call last):
elastalert_1     |       File "/opt/elastalert/elastalert/elastalert.py", line 1440, in alert
elastalert_1     |         return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
elastalert_1     |       File "/opt/elastalert/elastalert/elastalert.py", line 1529, in send_alert
elastalert_1     |         alert.alert(matches)
elastalert_1     |       File "/opt/elastalert/elastalert/alerts.py", line 924, in alert
elastalert_1     |         stdout, stderr = subp.communicate(input=alert_text)
elastalert_1     |       File "/usr/lib/python3.7/subprocess.py", line 949, in communicate
elastalert_1     |         self._stdin_write(input)
elastalert_1     |       File "/usr/lib/python3.7/subprocess.py", line 898, in _stdin_write
elastalert_1     |         self.stdin.write(input)
elastalert_1     |     TypeError: a bytes-like object is required, not 'str'
elastalert_1     |     
elastalert_1     |     
elastalert_1     | 15:06:46.697Z ERROR elastalert-server:
```

**Comment by mmguero** [comment]
Okay, apparently the base image on my build server for the elastalert container was not up-to-date when that was built. I have pushed a new build of the elastart container to docker hub:

```
malcolmnetsec/elastalert                            1.8.1               66251593748b        11 hours ago        398MB
```

With that container, my elastalert rule *does* trigger correctly:
```
elastalert_1     | 15:42:38.223Z  INFO elastalert-server:
elastalert_1     |     ProcessController:  Network traffic captured by filebeat generated a Scan::Address_Scan notice at 2020-01-24T15:42:10.290Z: "172.16.10.189 scanned at least 25 unique hosts on port 443/tcp in 2m25s"
elastalert_1     |     
```

**Comment by joel858** [comment]
The new images were able to give more verbose output for the containers. I had to just adjust bind mount permissions for /opt/elastalert/rules on the host. Seems to be a recurring issue for me with other bind mounts.
