### ISSUE TITLE
submitting hunt job crashes viewer unless Zeek logs are filtered out

### ISSUE THREAD

**Issue by mmguero** [cisagov/Malcolm#110]
Steps to reproduce:

1. populate the database with some data from a PCAP
2. wait for both the Moloch session records and the Zeek records to populate the database
3. go to the hunt page in moloch
4. submit a hunt job (without applying any other filters)

Expected results:

The hunt should examine the PCAP files, but for Zeek log records that don't have a PCAP file associated with them they should just be ignored

Actual results:

viewer continually crashes and restarts as the job status is checked:

```
moloch_1         | Mon, 03 Feb 2020 16:54:20 GMT tlacuache POST /hunt 200 357 bytes 230.189 ms
moloch_1         | url.js:154
moloch_1         |     throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
moloch_1         |     ^
moloch_1         |
moloch_1         | TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
moloch_1         |     at Url.parse (url.js:154:11)
moloch_1         |     at Object.urlParse [as parse] (url.js:148:13)
moloch_1         |     at /data/moloch/viewer/viewer.js:922:20
moloch_1         |     at /data/moloch/viewer/viewer.js:862:14
moloch_1         |     at exports.get (/data/moloch/viewer/db.js:812:7)
moloch_1         |     at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:327:9)
moloch_1         |     at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:267:7)
moloch_1         |     at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
moloch_1         |     at IncomingMessage.wrapper (/data/moloch/node_modules/lodash/lodash.js:4929:19)
moloch_1         |     at IncomingMessage.emit (events.js:203:15)
moloch_1         | Launch viewer...
```

The workaround is to make sure to apply the `PCAP Files` filter before submitting the hunt job: (ie., choose `PCAP Files` from the dropdown in this screenshot):

![Filters (choose PCAP Files)](https://user-images.githubusercontent.com/13872653/73673557-0c009b00-466c-11ea-8901-fa33f6b0e50c.png)

**Comment by mmguero** [comment]
External dependency: https://github.com/aol/moloch/issues/1374
